#!/bin/sh
# Top 10 of the most used passwords

if [ $# -le 0 ]
then
    echo "Get the top 10 of the most used passwords in a file"
    echo "Usage: $0 file.txt"
    exit 1
fi

sort "$1" | uniq -c | sort -nr | head
